services:
  - type: web
    name: samsim
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 180 --workers 2 wsgi:application
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONUNBUFFERED
        value: 1
