http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    flask-strip:
      stripPrefix:
        prefixes:
          - "/app"

    flask-script-name:
      headers:
        customRequestHeaders:
          X-Script-Name: "/app"

  routers:
    http-to-https:
      entryPoints:
        - web
      rule: Host(`dmikes.duckdns.org`)
      middlewares:
        - redirect-to-https
      service: noop@internal

    flask-app:
      rule: "Host(`dmikes.duckdns.org`) && PathPrefix(`/app`)"
      entryPoints:
        - websecure
      service: flask-native
      tls:
        certResolver: myresolver
      middlewares:
        - flask-strip
        - flask-script-name

  services:
    flask-native:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5001"

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      sessionTicket: {}
